name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]

env:
  PLATFORMS: linux/amd64, linux/arm64
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Tag or Branch
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAGS="${{ secrets.DOCKER_HUB_USERNAME }}/serles-certbot-cloudflare-proxy:latest, \
                  ${{ secrets.DOCKER_HUB_USERNAME }}/serles-certbot-cloudflare-proxy:${{ github.event.release.tag_name }}, \
                  ghcr.io/${{ github.repository_owner }}/serles-certbot-cloudflare-proxy:latest, \
                  ghcr.io/${{ github.repository_owner }}/serles-certbot-cloudflare-proxy:${{ github.event.release.tag_name }}"
          else
            TAGS="${{ secrets.DOCKER_HUB_USERNAME }}/serles-certbot-cloudflare-proxy:${GITHUB_REF##*/}, \
                  ghcr.io/${{ github.repository_owner }}/serles-certbot-cloudflare-proxy:${GITHUB_REF##*/}"
          fi
          TAGS="$TAGS, \
                ${{ secrets.DOCKER_HUB_USERNAME }}/serles-certbot-cloudflare-proxy:${{ github.sha }}, \
                ghcr.io/${{ github.repository_owner }}/serles-certbot-cloudflare-proxy:${{ github.sha }}"
          echo "docker_tags=$TAGS" >> $GITHUB_OUTPUT
          
      - name: Build and push to Docker Hub / GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.vars.outputs.docker_tags }}
